spring:
  data:
    mongodb:
      uri: mongodb+srv://deepak2004verma:Y2hUdoHXY2QPxxB9@cluster0.moxtp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: erpData

flask:
  server:
    url: http://127.0.0.1:5000
#    url: https://py-processor-production.up.railway.app

cors:
  allowed:
    origins: http://localhost:5173

#server:
#  servlet:
#    session:
#      cookie:
#        name: SESSIONID
#        path: /
#        http-only: true
#        secure: false
#        same-site: Lax
#        timeout: 30m