spring:
  data:
    mongodb:
#      uri: mongodb+srv://deepak2004verma:<db_password>@cluster0.moxtp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      uri: mongodb+srv://deepak2004verma:2kL65efz69QG5kf5@cluster0.moxtp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: erpData

flask:
  server:
    url: http://127.0.0.1:5000/
#    url: ${FLASK_SERVER_URL}

#server:
#  servlet:
#    session:
#      cookie:
#        name: SESSIONID
#        path: /
#        http-only: true
#        secure: false
#        same-site: Lax
#        timeout: 30m